name: root_keras
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pip:
    - numpy==1.19.0
    - matplotlib==3.2.2
    - scipy==1.4.1
    - tensorflow==2.2.0
    - scikit-learn==0.23.1

