name: root_keras
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - root
  - pip:
  	- numpy
  	- matplotlib
    - scipy==1.4.1
    - tensorflow==2.2.0
    - scikit-learn==0.23.1

